### ISSUE TITLE
KSP crashes in career mode when triggering achieved orbit automatic contract.

### ISSUE THREAD

**Issue by Paul-kingtiger** [KSP-64k/64k#14]
I'm getting a persistent bug in Career mode.  Launching you complete the various height and speed records, however when you get to orbit the game crashes.

This happens in KScale2 as well, so I'm guessing it's a Kopernicus bug.  I'll raise the issue there as well.

Question is, do we release anyway and make it clear career doesn't work, or hold on for a fix?

**Comment by Paul-kingtiger** [comment]
So this is a known bug with Kopernicus.  Guess we'll have to wait for a fix

**Comment by ricardo-zzz** [comment]
I refer to contract reach orbit right? I took an old save from 0.90 and no crashes so far

**Comment by Felger** [comment]
@NathanKell tracked this bug down, it's a slippery bugger! Looks like it's Kopernicus' load on demand interacting with something in stock at issue.  For the moment, disabling load on demand should fix it, until the Kopernicus team re-enables it.

[Fix in place here.](https://github.com/KSP-64k/64k/blob/master/GameData/64k/64K_Kopernicus_Stock_Planets.cfg#L3)

**Comment by Paul-kingtiger** [comment]
Awesome!  I'm testing this now, if it looks good I'll push out an update!

**Comment by Paul-kingtiger** [comment]
Doesn't seem to fix the issue.  I'm running on a clean install of KScale2 with latest Kopernicus, still getting the crash on achieving orbit.

**Comment by NathanKell** [comment]
@Paul-kingtiger  what's the exact cfg you're using? gist/pastebin?

**Comment by Paul-kingtiger** [comment]
@Kopernicus:AFTER[Kopernicus]
{
	%useOnDemand = false
	
	@Body[Sun]
    {
        @Properties
        {
			radius = 523200000
			@ScienceValues
			{
			}
        }
    }
	@Body[Moho]
    {
        @Properties
        {
			radius = 500000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 10526276608
        }
    }
	@Body[Eve]
    {
        @Properties
        {
			radius = 1400000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 19665369088
        }
    }
	@Body[Gilly]
    {
        @Properties
        {
			radius = 26000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 63000000
        }
    }
	@Body[Kerbin]
    {
        @Properties
        {
			radius = 1200000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 27199680512
        }
		ScaledVersion
		{
			Material
			{
				texture = KScale2/Textures/KScale_Kerbin
				normals = KScale2/Textures/KScale_Kerbin_NRM
			}
		}
		!SpaceCenter{}
        SpaceCenter
        {
            //PQSCity
            latitude = 0
            longitude = -74.7
            lodvisibleRangeMult = 6
            repositionRadiusOffset = 38
            
            // MapDecal
            decalLatitude = -0.215
            decalLongitude = -74.65
            heightMapDeformity = 65
            absoluteOffset = 0
            absolute = true
            radius = 13000
        }
    }
	@Body[Mun]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 400000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 24000000
        }
    }
	@Body[Minmus]
    {
        @Properties
        {
			radius = 120000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 94000000
        }
    }
	@Body[Duna]
    {
        @Properties
        {
			radius = 640000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 41452310528
        }
    }
	@Body[Ike]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 260000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 6400000
        }
    }
	@Body[Dres]
    {
        @Properties
        {
			radius = 276000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 81678696406
        }
    }
	@Body[Jool]
    {
        @Properties
        {
			radius = 12000000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 1.37547E+11
        }
    }
	@Body[Laythe]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 1000000 
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 54368000
        }
    }
	@Body[Vall]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 600000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 86304000
        }
    }
	@Body[Tylo]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 1200000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 137000000
        }
    }
	@Body[Bop]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 130000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 257000000
        }
    }
	@Body[Pol]
    {
        @Properties
        {
			tidallyLocked = true
			radius = 88000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 359780000
        }
    }
	@Body[Eeloo]
    {
        @Properties
        {
			radius = 420000
			@ScienceValues
			{
			}
        }
        @Orbit
        {
			semiMajorAxis = 1.80238E+11
        }
    }
}

**Comment by NathanKell** [comment]
Well huh. What's your player.log / output_log.txt show? Are there any OD: lines?

**Comment by Paul-kingtiger** [comment]
So I tried deleting my Steam install and downloading from scratch and since then I haven't been able to crash the game.  I'll keep testing but it looks like the fix works and there was something else, maybe a hang over from the older version causing the problem.

**Comment by Paul-kingtiger** [comment]
More testing today and I was able to get it to crash on orbit.

Output_log.txt
https://gist.github.com/Paul-kingtiger/7448a8c9d2b24fa8e4c1

**Comment by NathanKell** [comment]
Well, that's sad.
And OnDemand is definitely not running, no OD messages in the log.

Next try: set AllowGround to False in all instances in Contracts.cfg. According to the debug report above it's happening because ground surveys are failing.

**Comment by Paul-kingtiger** [comment]
Tried Kopernicus 4 with the contract fix removed, got the game to lock up on the 3rd attempt.
